### ISSUE TITLE
Love the library, is this still being maintained?

### ISSUE THREAD

**Issue by MattThyng** [tjrexer/react-notifications#17]
This is a great library, I was wondering if there is an estimate for the next release?

Thanks!

**Comment by tjrexer** [comment]
Yea, I'm doing what I can, juggling everything else right now.  Was doing front end when I originally reclaimed it from the original developer.  Since then I've changed companies & am now focused on back end, so don't use this like I did in my last projects.  I'm open to having collaborators help maintain it.  Review the [contributing](https://github.com/tjrexer/react-notifications/blob/master/README.md#contributing) section of the read me and submit a PR for what you want to fix.
